### ISSUE TITLE
UAAS Installation

### ISSUE THREAD

**Issue by villian** [ryanlewis/seo-metadata#26]
We tried to install package via dev environment and local, result is the same, files were added to project, only package to the installed packages list.

In trace log we have error - 

Package install error
System.IO.FileNotFoundException: Could not find file '\App_Data\de077751-4ac9-4dff-be60-165e64420691\serp2.png.png'.
File name: '\App_Data\de077751-4ac9-4dff-be60-165e64420691\serp2.png.png'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at umbraco.cms.businesslogic.packager.Installer.InstallFiles(Int32 packageId, String tempDir)

**Comment by ryanlewis** [comment]
This might be related to #25. 

I'll hopefully have a look at this in the next couple of days. In the meantime, I would recommend installing the package via Nuget if that option is available to you.

**Comment by villian** [comment]
Thanks, we already installed it via nuGet

**Comment by rwilchek** [comment]
Hi,
   Any updates on this issue?  I have a server that does not have VS installed on it and is already in production.  I realize Nuget works and the package installer does not, but I have a situation where I want to add it to my production server and was wondering if there is a way to get .4 to install without nuget or a way to migrate what I have in my dev server over to my production server.

Thanks!

Robert

**Comment by ryanlewis** [comment]
Might hopefully be able to look at this next week - I’m currently due to
start a new Umbraco project then, so should be able to provide a little
love to this project then.

On 28 September 2016 at 16:07:50, rwilchek (notifications@github.com) wrote:

Hi,
Any updates on this issue? I have a server that does not have VS installed
on it and is already in production. I realize Nuget works and the package
installer does not, but I have a situation where I want to add it to my
production server and was wondering if there is a way to get .4 to install
without nuget or a way to migrate what I have in my dev server over to my
production server.

Thanks!

Robert

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/ryanlewis/seo-metadata/issues/26#issuecomment-250193890,
or mute the thread

**Comment by sebastiandammark** [comment]
I have the same issue. And I don't have access to NuGet.
Is this package still maintained ?

**Comment by ryanlewis** [comment]
Hi @sebastiandammark

I don’t work with Umbraco anymore, so this project is no longer maintained by myself, although would happily accept PRs and contributions if required. I suspect there may be better alternatives out there nowadays.

**Comment by ryanlewis** [comment]
Closing — this repository is archived. The package targets Umbraco 7, which has been unsupported upstream for years.
